// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using love2hina.Windows.MAUI.PhotoViewer.Common.Database;

#nullable disable

namespace love2hina.Windows.MAUI.PhotoViewer.Common.Migrations
{
    [DbContext(typeof(FirebirdContext))]
    [Migration("20230108140147_v0001")]
    partial class v0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("love2hina.Windows.MAUI.PhotoViewer.Common.Database.Entities.ThumbnailCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexHash")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReferenced")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<byte[]>("PngData")
                        .HasColumnType("BLOB SUB_TYPE BINARY");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LastReferenced" }, "IDX_Date");

                    b.HasIndex(new[] { "IndexHash", "Path" }, "IDX_Path");

                    b.ToTable("ThumbnailCaches");
                });
#pragma warning restore 612, 618
        }
    }
}
